# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.8.0
        environment:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/flask-graphql-boilerplate-ci

      # CircleCI PostgreSQL image
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: flask-graphql-boilerplate-ci
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export FLASK_ENV="CI"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR} # prints: XXXXXXX
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov=app
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
